import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :atlas, AtlasWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
# config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Atlas.Finch

# Disable Swoosh Local Memory Storage
# config :swoosh, local: false

# Do not print debug messages in production
# config :logger, level: :info

config :logger, :console,
  format: "[$level] $message\n",
  metadata: [:request_id],
  level: :info

# config :atlas, Atlas.Mailer,
#   adapter: Bamboo.SendGridAdapter,
#   api_key: System.get_env("SENDGRID_API_KEY"),
#   no_reply_email: System.get_env("SENDGRID_NO_REPLY_EMAIL"),
#   hackney_opts: [
#     recv_timeout: :timer.minutes(1)
#   ]

config :atlas, Atlas.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: "smtp.gmail.com",
  hostname: "gmail.com",
  port: 465,
  username: System.get_env("SMTP_USERNAME"),
  password: System.get_env("SMTP_PASSWORD"),
  tls: :never,
  ssl: true,
  retries: 1,
  verify: :verify_peer,
  from: System.get_env("SMTP_FROM_NAME")

config :sentry,
  dsn: "https://00e225f922e6a462aa68952f60c6fa5e@sentry.atlas.com/4",
  environment_name: Mix.env(),
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()]

# Enable dev routes for dashboard and mailbox
config :atlas, dev_routes: true

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
